# compose.yaml
services:
    php:
        # uncomment the following line if you want to use a custom Dockerfile
        build:
            context: docker/franken
        # uncomment the following line if you want to run this in a production environment
        restart: always
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
            - "443:443/udp" # HTTP/3
        volumes:
            - ./app/symfony:/app
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - mysql
            - mercure
        # comment the following line in production, it allows to have nice human-readable logs in dev
        tty: true
        environment:
            - FRANKENPHP_CONFIG=worker ./public/index.php
            - CADDY_GLOBAL_OPTIONS=debug
            - APP_RUNTIME:Runtime\\FrankenPhpSymfony\\Runtime
            - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-azerty}@mysql/${MYSQL_DATABASE:-symfony}

    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
            MYSQL_USER: ${MYSQL_USER:-symfony}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
        volumes:
            - mysql_test_data:/var/lib/mysql

    phpmyadmin:
        image: nazarpc/phpmyadmin
        depends_on:
            - mysql

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins https://localhost
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config
# Volumes needed for Caddy certificates and configuration
volumes:
    caddy_data:
    caddy_config:
    mysql_test_data:
    mercure_data:
    mercure_config: